// Generated by gencpp from file ros_mhlmt_msgs/mhlmt_joystick_dataRequest.msg
// DO NOT EDIT!


#ifndef ROS_MHLMT_MSGS_MESSAGE_MHLMT_JOYSTICK_DATAREQUEST_H
#define ROS_MHLMT_MSGS_MESSAGE_MHLMT_JOYSTICK_DATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_mhlmt_msgs
{
template <class ContainerAllocator>
struct mhlmt_joystick_dataRequest_
{
  typedef mhlmt_joystick_dataRequest_<ContainerAllocator> Type;

  mhlmt_joystick_dataRequest_()
    : state(false)  {
    }
  mhlmt_joystick_dataRequest_(const ContainerAllocator& _alloc)
    : state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct mhlmt_joystick_dataRequest_

typedef ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<std::allocator<void> > mhlmt_joystick_dataRequest;

typedef boost::shared_ptr< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest > mhlmt_joystick_dataRequestPtr;
typedef boost::shared_ptr< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest const> mhlmt_joystick_dataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_mhlmt_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "001fde3cab9e313a150416ff09c08ee4";
  }

  static const char* value(const ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x001fde3cab9e313aULL;
  static const uint64_t static_value2 = 0x150416ff09c08ee4ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_mhlmt_msgs/mhlmt_joystick_dataRequest";
  }

  static const char* value(const ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool state\n\
";
  }

  static const char* value(const ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mhlmt_joystick_dataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_MHLMT_MSGS_MESSAGE_MHLMT_JOYSTICK_DATAREQUEST_H
