// Generated by gencpp from file ros_mhlmt_msgs/mhlmt_joystick_data.msg
// DO NOT EDIT!


#ifndef ROS_MHLMT_MSGS_MESSAGE_MHLMT_JOYSTICK_DATA_H
#define ROS_MHLMT_MSGS_MESSAGE_MHLMT_JOYSTICK_DATA_H

#include <ros/service_traits.h>


#include <ros_mhlmt_msgs/mhlmt_joystick_dataRequest.h>
#include <ros_mhlmt_msgs/mhlmt_joystick_dataResponse.h>


namespace ros_mhlmt_msgs
{

struct mhlmt_joystick_data
{

typedef mhlmt_joystick_dataRequest Request;
typedef mhlmt_joystick_dataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mhlmt_joystick_data
} // namespace ros_mhlmt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mhlmt_msgs::mhlmt_joystick_data > {
  static const char* value()
  {
    return "1329a64fad65e08bad5df97dce71b9e1";
  }

  static const char* value(const ::ros_mhlmt_msgs::mhlmt_joystick_data&) { return value(); }
};

template<>
struct DataType< ::ros_mhlmt_msgs::mhlmt_joystick_data > {
  static const char* value()
  {
    return "ros_mhlmt_msgs/mhlmt_joystick_data";
  }

  static const char* value(const ::ros_mhlmt_msgs::mhlmt_joystick_data&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest> should match 
// service_traits::MD5Sum< ::ros_mhlmt_msgs::mhlmt_joystick_data > 
template<>
struct MD5Sum< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mhlmt_msgs::mhlmt_joystick_data >::value();
  }
  static const char* value(const ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest> should match 
// service_traits::DataType< ::ros_mhlmt_msgs::mhlmt_joystick_data > 
template<>
struct DataType< ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mhlmt_msgs::mhlmt_joystick_data >::value();
  }
  static const char* value(const ::ros_mhlmt_msgs::mhlmt_joystick_dataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mhlmt_msgs::mhlmt_joystick_dataResponse> should match 
// service_traits::MD5Sum< ::ros_mhlmt_msgs::mhlmt_joystick_data > 
template<>
struct MD5Sum< ::ros_mhlmt_msgs::mhlmt_joystick_dataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mhlmt_msgs::mhlmt_joystick_data >::value();
  }
  static const char* value(const ::ros_mhlmt_msgs::mhlmt_joystick_dataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mhlmt_msgs::mhlmt_joystick_dataResponse> should match 
// service_traits::DataType< ::ros_mhlmt_msgs::mhlmt_joystick_data > 
template<>
struct DataType< ::ros_mhlmt_msgs::mhlmt_joystick_dataResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mhlmt_msgs::mhlmt_joystick_data >::value();
  }
  static const char* value(const ::ros_mhlmt_msgs::mhlmt_joystick_dataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MHLMT_MSGS_MESSAGE_MHLMT_JOYSTICK_DATA_H
