// Generated by gencpp from file ros_mhlmt_msgs/mhmlt_control_service.msg
// DO NOT EDIT!


#ifndef ROS_MHLMT_MSGS_MESSAGE_MHMLT_CONTROL_SERVICE_H
#define ROS_MHLMT_MSGS_MESSAGE_MHMLT_CONTROL_SERVICE_H

#include <ros/service_traits.h>


#include <ros_mhlmt_msgs/mhmlt_control_serviceRequest.h>
#include <ros_mhlmt_msgs/mhmlt_control_serviceResponse.h>


namespace ros_mhlmt_msgs
{

struct mhmlt_control_service
{

typedef mhmlt_control_serviceRequest Request;
typedef mhmlt_control_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mhmlt_control_service
} // namespace ros_mhlmt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mhlmt_msgs::mhmlt_control_service > {
  static const char* value()
  {
    return "22c7c465d64c7e74c6ae22029c7ca150";
  }

  static const char* value(const ::ros_mhlmt_msgs::mhmlt_control_service&) { return value(); }
};

template<>
struct DataType< ::ros_mhlmt_msgs::mhmlt_control_service > {
  static const char* value()
  {
    return "ros_mhlmt_msgs/mhmlt_control_service";
  }

  static const char* value(const ::ros_mhlmt_msgs::mhmlt_control_service&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mhlmt_msgs::mhmlt_control_serviceRequest> should match 
// service_traits::MD5Sum< ::ros_mhlmt_msgs::mhmlt_control_service > 
template<>
struct MD5Sum< ::ros_mhlmt_msgs::mhmlt_control_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mhlmt_msgs::mhmlt_control_service >::value();
  }
  static const char* value(const ::ros_mhlmt_msgs::mhmlt_control_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mhlmt_msgs::mhmlt_control_serviceRequest> should match 
// service_traits::DataType< ::ros_mhlmt_msgs::mhmlt_control_service > 
template<>
struct DataType< ::ros_mhlmt_msgs::mhmlt_control_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mhlmt_msgs::mhmlt_control_service >::value();
  }
  static const char* value(const ::ros_mhlmt_msgs::mhmlt_control_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mhlmt_msgs::mhmlt_control_serviceResponse> should match 
// service_traits::MD5Sum< ::ros_mhlmt_msgs::mhmlt_control_service > 
template<>
struct MD5Sum< ::ros_mhlmt_msgs::mhmlt_control_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mhlmt_msgs::mhmlt_control_service >::value();
  }
  static const char* value(const ::ros_mhlmt_msgs::mhmlt_control_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mhlmt_msgs::mhmlt_control_serviceResponse> should match 
// service_traits::DataType< ::ros_mhlmt_msgs::mhmlt_control_service > 
template<>
struct DataType< ::ros_mhlmt_msgs::mhmlt_control_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mhlmt_msgs::mhmlt_control_service >::value();
  }
  static const char* value(const ::ros_mhlmt_msgs::mhmlt_control_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MHLMT_MSGS_MESSAGE_MHMLT_CONTROL_SERVICE_H
