// Generated by gencpp from file ros_mhmlt_msgs/mhmlt_joystick_data.msg
// DO NOT EDIT!


#ifndef ROS_MHMLT_MSGS_MESSAGE_MHMLT_JOYSTICK_DATA_H
#define ROS_MHMLT_MSGS_MESSAGE_MHMLT_JOYSTICK_DATA_H

#include <ros/service_traits.h>


#include <ros_mhmlt_msgs/mhmlt_joystick_dataRequest.h>
#include <ros_mhmlt_msgs/mhmlt_joystick_dataResponse.h>


namespace ros_mhmlt_msgs
{

struct mhmlt_joystick_data
{

typedef mhmlt_joystick_dataRequest Request;
typedef mhmlt_joystick_dataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mhmlt_joystick_data
} // namespace ros_mhmlt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_mhmlt_msgs::mhmlt_joystick_data > {
  static const char* value()
  {
    return "00a7ccec808b16c3b52f1eea2d823951";
  }

  static const char* value(const ::ros_mhmlt_msgs::mhmlt_joystick_data&) { return value(); }
};

template<>
struct DataType< ::ros_mhmlt_msgs::mhmlt_joystick_data > {
  static const char* value()
  {
    return "ros_mhmlt_msgs/mhmlt_joystick_data";
  }

  static const char* value(const ::ros_mhmlt_msgs::mhmlt_joystick_data&) { return value(); }
};


// service_traits::MD5Sum< ::ros_mhmlt_msgs::mhmlt_joystick_dataRequest> should match 
// service_traits::MD5Sum< ::ros_mhmlt_msgs::mhmlt_joystick_data > 
template<>
struct MD5Sum< ::ros_mhmlt_msgs::mhmlt_joystick_dataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mhmlt_msgs::mhmlt_joystick_data >::value();
  }
  static const char* value(const ::ros_mhmlt_msgs::mhmlt_joystick_dataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mhmlt_msgs::mhmlt_joystick_dataRequest> should match 
// service_traits::DataType< ::ros_mhmlt_msgs::mhmlt_joystick_data > 
template<>
struct DataType< ::ros_mhmlt_msgs::mhmlt_joystick_dataRequest>
{
  static const char* value()
  {
    return DataType< ::ros_mhmlt_msgs::mhmlt_joystick_data >::value();
  }
  static const char* value(const ::ros_mhmlt_msgs::mhmlt_joystick_dataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_mhmlt_msgs::mhmlt_joystick_dataResponse> should match 
// service_traits::MD5Sum< ::ros_mhmlt_msgs::mhmlt_joystick_data > 
template<>
struct MD5Sum< ::ros_mhmlt_msgs::mhmlt_joystick_dataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_mhmlt_msgs::mhmlt_joystick_data >::value();
  }
  static const char* value(const ::ros_mhmlt_msgs::mhmlt_joystick_dataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_mhmlt_msgs::mhmlt_joystick_dataResponse> should match 
// service_traits::DataType< ::ros_mhmlt_msgs::mhmlt_joystick_data > 
template<>
struct DataType< ::ros_mhmlt_msgs::mhmlt_joystick_dataResponse>
{
  static const char* value()
  {
    return DataType< ::ros_mhmlt_msgs::mhmlt_joystick_data >::value();
  }
  static const char* value(const ::ros_mhmlt_msgs::mhmlt_joystick_dataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MHMLT_MSGS_MESSAGE_MHMLT_JOYSTICK_DATA_H
